version: '3'
services:
#Service odoo
 odoo:
  build: ./odoo
  hostname: odoo
  depends_on:
  - postgres
  ports:
  - "8069:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - /root/odoo:/opt/odoo/src
  - /root/odoo/conf:/opt/odoo/conf
  - /root/odoo/log:/var/log/odoo
  networks:
   odoo_2container:
    ipv4_address: 192.168.199.13
#Service postgres
 postgres:
  build: ./postgres
  hostname: postgres
  volumes:
  - pg_data:/var/lib/postgresql/11/main
  networks:
   odoo_2container:
    ipv4_address: 192.168.199.10
volumes:
  pg_data:
networks:
  odoo_2container:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.199.0/24
