version: '3'
services:
#Service odoo toma el Dockerfile de ./build/odoo13
 odoo:
  build: ./odoo
  hostname: odoo
  #Mapea el 8069 del container al anfitrión
  ports:
  - "8069:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - /root/odoo:/opt/odoo/src
