version: '3'
services:
#Service odoo toma el Dockerfile de ./build/odoo
 odoo1:
  build: ./odoo
  hostname: odoo1
  depends_on:
  - postgres
  ports:
  - "8069:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - /root/odoo/src:/opt/odoo/src
  - odoo_filestore:/opt/odoo/.local/share/Odoo
  networks:
   nginx_odoo_ssl:
    ipv4_address: 192.168.201.101
 odoo2:
  build: ./odoo
  hostname: odoo2
  depends_on:
  - postgres
  ports:
  - "8070:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - /root/odoo/src:/opt/odoo/src
  - odoo_filestore:/opt/odoo/.local/share/Odoo
  networks:
   nginx_odoo_ssl:
    ipv4_address: 192.168.201.102
 postgres:
  build: ./postgres
  hostname: postgres
  volumes:
  - pg_data_proxy:/var/lib/postgresql/11/main
  networks:
   nginx_odoo_ssl:
    ipv4_address: 192.168.201.103
 nginx:
  build: ./nginx
  hostname: nginx
  ports:
  - "80:80"
  - "443:443"
  networks:
   nginx_odoo_ssl:
    ipv4_address: 192.168.201.100
  volumes:
  - nginx_ssl_conf:/etc/nginx
networks:
  nginx_odoo_ssl:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.201.0/24
volumes:
  nginx_ssl_conf:
  pg_data_proxy:
  odoo_filestore:
   
