version: '3'
services:
#Service odoo toma el Dockerfile de ./build/odoo
 odoo1:
  build: ./odoo
  hostname: odoo1
  ports:
  - "8069:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - /root/odoo/src:/opt/odoo/src
  - /root/odoo/conf:/opt/odoo/conf
  - /root/odoo/log:/var/log/odoo
  networks:
   nginx_odoo:
    ipv4_address: 192.168.200.101
 odoo2:
  build: ./odoo
  hostname: odoo2
  ports:
  - "8070:8069"
  #Mapeo del directorio de la MV en el container
  volumes:
  - /root/odoo/src:/opt/odoo/src
  - /root/odoo/conf:/opt/odoo/conf
  - /root/odoo/log:/var/log/odoo
  networks:
   nginx_odoo:
    ipv4_address: 192.168.200.102
 nginx:
  build: ./nginx
  hostname: nginx
  ports:
  - "80:80"
  networks:
   nginx_odoo:
    ipv4_address: 192.168.200.100
  volumes:
  - nginx_conf:/etc/nginx
networks:
  nginx_odoo:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.200.0/24
volumes:
  nginx_conf:
   
