version: '2'
services:
#Service odoo toma el Dockerfile de ./build/odoo13
 odoo:
  build: ./odoo
  ports:
  - "8069:8069"
  #Cambiarlo para el home de cada usuario
  volumes:
  - /home/javierfp/odoo:/opt/odoo/src
  - /home/javierfp/odoo/conf:/opt/odoo/conf
  - /home/javierfp/odoo/log:/var/log/odoo
